### ISSUE TITLE
WavTokenizer

### ISSUE THREAD

**Issue by jishengpeng** [Stability-AI/stable-codec#2]
Hello, great work! I am the author of [WavTokenizer](https://github.com/jishengpeng/WavTokenizer) (a similar low-bitrate attention codec). Do you have any plans to include a comparison with WavTokenizer? Thank you very much.

**Comment by julian-parker** [comment]
Hi! Great work on WavTokenizer! We're not planning to add any more evals to the paper at this point. We may do some comparisons on the open-weights version of the model (there will be slightly different variants compared to the paper), in which case WavTokenizer is indeed a good candidate for inclusion.
